services:
  backend-service:
    image: xyzassessment/backend-services:latest
    restart: always
    ports:
      - 8080:8080
  aggregation:
    build: .
    depends_on:
      - backend-service
    environment:
          - backend.service.url=http://backend-service:8080
    ports:
      - 8081:8081
