server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: AggregationApi

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic

backend.service.url: http://localhost:8080
service.call.batch.size: 5
service.call.batch.timeout: 5
service.call.threadpool.size: 10
batch.call.threadpool.size: 10


